# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 343811dd863c82665593ae4a0380c09a0a5699a357d0eb7445ef7ce4de9f443242a2275c463cc47fe0bc08642ef4d7f879302036b6c849e36e35f2a662aca2c4

test:
  secret_key_base: 762fb6094ac5e2eac672caaa7c9336b81e843b89da68483c50734a0bf887f4c1de8c94bbdb379eae66497c500011c75ace2f3920f05b6a08964bacd57d90d266

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
